language: node_js
node_js:
  - "node"
before_install: cd website
deploy:
  provider: script
  skip-cleanup: true
  script:
    - git config --global user.name "${GIT_USER}"
    - git config --global user.email "${GIT_EMAIL}"
    - echo "machine github.com login ${GIT_USER} password ${GITHUB_TOKEN}" > ~/.netrc
    - npm install && GIT_USER="${GIT_USER}" npm run publish-gh-pages
  on:
    branch: master
